### PR TITLE
Antoine webapp structure prototype: The entire project skeleton and working prototype

### PR DESCRIPTION
**Pull request by ChiefsBestPal**
Please merge this branch and all my commits. There are A LOT of files and folders that need to joined to the main branch before the home page PR or any other should be merged. Review as you wish, I left READMEs with instruction on how to run the prototype. 

Else I will have to explain to you all the integration and etc in a future meeting.
I already did so with @SenecalRenaud, so you are my reviewer of choice right now :D 

I will create issues later on ! Please contact me when you are ready for them!

Cheers !

### CODE REVIEW

**Comment by SenecalRenaud** [comment]
Should the CommentPost class in backend/app.py be in the models.py file or is it in app.py for a specific reason?

**Comment by SenecalRenaud** [comment]
Are all the requirements listed in backend/requirements.txt absolutely necessary to be able to run the website?

**Comment by ChiefsBestPal** [comment]
> Are all the requirements listed in backend/requirements.txt absolutely necessary to be able to run the website?

Yes. The actual amount of stuff that is pip installed if you do it manually is much less. This how the entire framework of the backend/API I set up operates, no need to read this unless you have a another/better way to structure the API already implemented.
just do "pip install -r requirements.txt"

**Comment by ChiefsBestPal** [comment]
> Should the CommentPost class in backend/app.py be in the models.py file or is it in app.py for a specific reason?

I transferred everything to their corresponding modules and added the needed code in app.py for integration. It was only there so that when I was learning all the libraries, packages and testing everything together; it was simpler to rework and change. 

Now all is in place. We should focus on database hosting so we can integrate a non local version soon. 
Merge my PR asap when you are ready please. @SenecalRenaud It contains the entire core of the project and it would be interesting to show in main branch during the meeting tonight.

**Comment by Spiratatoe** [comment]
will accept, core project structure should be merged before sprint showcase asap

**Pull request merged**
