### PR TITLE
Notification demo and job posting database

### LINKED ISSUE #2: Send emails when chosen for interview
As a Job Seeker, I would like to receive an email notification if i get accepted for an interview

auto send emails if chosen for interview, 
will need to use the email set to the users account

### LINKED ISSUE #4: Implement Job Posting
As an employer, I would like to be able to post job applications for people to apply to.

Subtasks:
- Create system for posting applications (filling a form?)
- Give Employer accounts permission to post applications
- Give Employer and Admin accounts permission to edit/remove applications

### PR DESCRIPTION
**Pull request by ozan1318**
Creates new MySQL Table to store job posting data, adds methods to store job postings in the table from the existing webpage.

Uses flask-mail and the shared gmail account to send emails to user (currently just a test method).

### CODE REVIEW

**Comment by ozan1318** [comment]
If you would like to test the flask-mail demo, ask me for an application password and enter it to the empty string in line 52 of config.py

**Comment by ozan1318** [comment]
Don't merge yet, there is a small issue in the job posting db schema I need to fix

**Comment by ChiefsBestPal** [comment]
> Don't merge yet, there is a small issue in the job posting db schema I need to fix

Alright. The models, the sql schemas and overall it looks fine.  Once you are done fixing the schema bug fixing, 
could you make a scrum meeting with me so i can review in actuality the notification system when you receive them on your personal email ?

We could setup the email for notifications to be the 'equipeboucani' gmail one you made.

@ozan1318 Once you are ready contact me, the code is well integrated so it wont take too much time to test and then merge to main. Also this PR should be merged and closed before the one I made for my 'user-system-firebase' branch since it is very large, it will be easier for us to make it work once your notification system is in 'main'.

**Comment by ChiefsBestPal** [comment]
After scrum meeting with you in person, this branch is needed and will integrate well with the progress. 

I will directly merge this branch so we can make use of the notification system.

**Comment by ChiefsBestPal** [comment]
Fixed minor conflicts and TRAVIS CI Integration tests passed. Merging pull request

**Pull request merged**
